# Generated by Django 5.0.3 on 2024-03-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
