# Generated by Django 5.0.3 on 2024-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default='2024-12-12'),
            preserve_default=False,
        ),
    ]
