# Generated by Django 5.0.3 on 2024-03-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
    ]
