# Generated by Django 5.0.3 on 2024-03-11 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedOTP',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('email', models.EmailField(max_length=255)),
                ('otp', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
