# Generated by Django 5.0.3 on 2024-03-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_unverifiedotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnverifiedOTP',
        ),
    ]
