# Generated by Django 5.0.3 on 2024-03-11 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='ac',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='room.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room.room'),
        ),
    ]
