# Generated by Django 5.0.3 on 2024-03-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_amenities_ac_alter_amenities_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='ac',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
