# Generated by Django 5.0.3 on 2024-03-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_amenities_ac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='room.room'),
        ),
    ]
