# Generated by Django 5.0.3 on 2024-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_amenities_ac_alter_amenities_free_cable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=4, upload_to='room_images/'),
            preserve_default=False,
        ),
    ]
