# Generated by Django 5.0.3 on 2024-03-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
