# Generated by Django 5.0.3 on 2024-03-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_room_amenities_delete_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
