# Generated by Django 5.0.3 on 2024-03-15 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_room_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.AddField(
            model_name='room',
            name='district',
            field=models.CharField(default=5, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('item', models.CharField(max_length=250)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='room.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
