# Generated by Django 5.0.3 on 2024-03-15 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_remove_room_amenities_room_district_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='room.room'),
        ),
    ]
