# Generated by Django 5.0.3 on 2024-03-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_alter_amenities_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='district',
            new_name='city',
        ),
    ]
