# Generated by Django 5.0.3 on 2024-03-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_rename_district_room_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(max_length=250),
        ),
    ]
