# Generated by Django 5.0.3 on 2024-03-14 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_room_image'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='landlord_email',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='room',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
            preserve_default=False,
        ),
    ]
