# Generated by Django 5.0.3 on 2024-03-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_enquiry_landlord_email_enquiry_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='phone_no',
            new_name='mobile_no',
        ),
    ]
